# Generated by Django 5.1.1 on 2024-11-29 21:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('testwise_main', '0002_pdf_user_alter_pdf_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='pdf',
            name='analysis',
            field=models.TextField(blank=True, null=True),
        ),
    ]
