# Generated by Django 5.1.1 on 2024-12-23 19:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('testwise_main', '0004_document'),
    ]

    operations = [
        migrations.AddField(
            model_name='pdf',
            name='analyzed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
